### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by BigXJazz** [ChrisRisner/feedback#14]
Hi, i try to develop a Azure Notification Hub and Im very thankfull for your tutorial.
I want a service like whatsapp, so i need a unique Tag for every user (their id).
Can you tell me how to register a devicec with the right tag?

Greetings

**Comment by ChrisRisner** [comment]
How are you authenticating the user?  The simplest suggestion would be after they have logged in, get their user ID / User name / whatever unique identifier you get from the auth system and register that as a tag for the user.  Then when you want to push to them, you push to that user ID.  In order to ensure someone can't do something naughty and register as a user they aren't, you'd want a backend you can call into that KNOWS they're the user they say they are and can register the tag on their behalf so you're not doing the registering directly from the device.
